### PR TITLE
fix #148. Upgrades to Python 3.9.2

### LINKED ISSUE #148: Upgrading the machine
Some of our tools need a bit of love.

### PR DESCRIPTION
**Pull request by karlcow**

### CODE REVIEW

**Comment by karlcow** [comment]
I keep at CircleCi.

https://app.circleci.com/pipelines/github/webcompat/webcompat-metrics-server/25/workflows/19bbc57c-5af1-4561-a01c-f64fcaf68a1d/jobs/212

Maybe something has to change in the config.

```
Using SSH Config Dir '/home/circleci/.ssh'
git version 2.25.1
Cloning git repository
Cloning into '.'...
Warning: Permanently added the ECDSA host key for IP address '*****' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

exit status 128

CircleCI received exit code 128
```

**Comment by karlcow** [comment]
ok fixed it. removing and adding again the key, made it possible.
https://discuss.circleci.com/t/git-github-com-permission-denied-publickey/41000

**Comment by karlcow** [comment]
And Now it's on the side of Heroku where it seems to be failing :) 

Capture d’écran 2022-04-05 à 14 04 12

**Review by laghee — APPROVED** [review]
LGTM! Seems like Heroku's ok now, too (the time stamps are confusing me because I can't remember what zone Heroku's servers are in, but the build from this push appears to have completed successfully). 👍

**Comment by karlcow** [comment]
Thanks @laghee

**Comment by karlcow** [comment]
Ah oopsy

**Comment by karlcow** [comment]
Capture d’écran 2022-04-05 à 21 41 55

**Comment by karlcow** [comment]
```http
HTTP/1.1 500 INTERNAL SERVER ERROR
Connection: keep-alive
Server: gunicorn
Date: Tue, 05 Apr 2022 12:43:35 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 290
Via: 1.1 vegur
```

**Comment by karlcow** [comment]
ok the log failing. 

```
Apr 05 12:50:06 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981887199776821&selected=1447981887199776821) [app/web.1](https://my.papertrailapp.com/events?q=program%3Aapp%2Fweb.1&focus=1447981887199776821&selected=1447981887199776821) [10.1.92.81](https://my.papertrailapp.com/systems/webcompat-metrics/events?q=%2210.1.92.81%22&focus=1447981887199776821&selected=1447981887199776821) - - [05/Apr/2022:12:50:06 +0000] "GET /data/needstriage-timeline?from=2022-03-05&to=2022-04-05&=undefined HTTP/1.1" 500 290 "[https://webcompat-dashboard.herokuapp.com/](https://my.papertrailapp.com/systems/webcompat-metrics/events?q=%22https%3A%2F%2Fwebcompat-dashboard.herokuapp.com%2F%22&focus=1447981887199776821&selected=1447981887199776821)" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0"
Apr 05 12:50:08 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981892982788098&selected=1447981892982788098) [heroku/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aheroku%2Fscheduler.4027&focus=1447981892982788098&selected=1447981892982788098) Starting process with command `python3 bin/get_count.py sitewait`
Apr 05 12:50:08 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981894694236225&selected=1447981894694236225) [app/api](https://my.papertrailapp.com/events?q=program%3Aapp%2Fapi&focus=1447981894694236225&selected=1447981894694236225) Starting process with command `python3 bin/get_count.py sitewait` by user [scheduler@addons.heroku.com](https://my.papertrailapp.com/systems/webcompat-metrics/events?q=%22scheduler%40addons.heroku.com%22&focus=1447981894694236225&selected=1447981894694236225)
Apr 05 12:50:08 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981895701438464&selected=1447981895701438464) [heroku/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aheroku%2Fscheduler.4027&focus=1447981895701438464&selected=1447981895701438464) State changed from starting to up
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859332&selected=1447981902629859332) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859332&selected=1447981902629859332) /app/.heroku/python/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py:872: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859333&selected=1447981902629859333) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859333&selected=1447981902629859333)   warnings.warn(FSADeprecationWarning(
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859334&selected=1447981902629859334) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859334&selected=1447981902629859334) Traceback (most recent call last):
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859335&selected=1447981902629859335) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859335&selected=1447981902629859335)   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859336&selected=1447981902629859336) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859336&selected=1447981902629859336)     return self.registry[key]
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859337&selected=1447981902629859337) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859337&selected=1447981902629859337) KeyError: <greenlet.greenlet object at 0x7f8e5008aca0 (otid=0x7f8e4fca9e80) current active started main>
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859339&selected=1447981902629859339) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859339&selected=1447981902629859339) During handling of the above exception, another exception occurred:
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859341&selected=1447981902629859341) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859341&selected=1447981902629859341) Traceback (most recent call last):
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859342&selected=1447981902629859342) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859342&selected=1447981902629859342)   File "/app/bin/get_count.py", line 118, in <module>
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859343&selected=1447981902629859343) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859343&selected=1447981902629859343)     sys.exit(main())
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859344&selected=1447981902629859344) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859344&selected=1447981902629859344)   File "/app/bin/get_count.py", line 98, in main
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859345&selected=1447981902629859345) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859345&selected=1447981902629859345)     db.session.add(iss_count)
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859346&selected=1447981902629859346) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859346&selected=1447981902629859346)   File "<string>", line 2, in add
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859347&selected=1447981902629859347) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859347&selected=1447981902629859347)   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 24, in _proxied
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859348&selected=1447981902629859348) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859348&selected=1447981902629859348)     return self.registry()
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859349&selected=1447981902629859349) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859349&selected=1447981902629859349)   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859350&selected=1447981902629859350) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859350&selected=1447981902629859350)     return self.registry.setdefault(key, self.createfunc())
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859351&selected=1447981902629859351) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859351&selected=1447981902629859351)   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4205, in __call__
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859352&selected=1447981902629859352) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859352&selected=1447981902629859352)     return self.class_(**local_kw)
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859353&selected=1447981902629859353) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859353&selected=1447981902629859353)   File "/app/.heroku/python/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 176, in __init__
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859354&selected=1447981902629859354) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859354&selected=1447981902629859354)     bind = options.pop('bind', None) or db.engine
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859355&selected=1447981902629859355) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859355&selected=1447981902629859355)   File "/app/.heroku/python/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 998, in engine
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859356&selected=1447981902629859356) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859356&selected=1447981902629859356)     return self.get_engine()
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859357&selected=1447981902629859357) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859357&selected=1447981902629859357)   File "/app/.heroku/python/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1017, in get_engine
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859358&selected=1447981902629859358) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859358&selected=1447981902629859358)     return connector.get_engine()
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859359&selected=1447981902629859359) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859359&selected=1447981902629859359)   File "/app/.heroku/python/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 594, in get_engine
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859360&selected=1447981902629859360) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859360&selected=1447981902629859360)     self._engine = rv = self._sa.create_engine(sa_url, options)
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859361&selected=1447981902629859361) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859361&selected=1447981902629859361)   File "/app/.heroku/python/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1027, in create_engine
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859362&selected=1447981902629859362) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859362&selected=1447981902629859362)     return sqlalchemy.create_engine(sa_url, **engine_opts)
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859363&selected=1447981902629859363) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859363&selected=1447981902629859363)   File "<string>", line 2, in create_engine
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859364&selected=1447981902629859364) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859364&selected=1447981902629859364)   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 309, in warned
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859365&selected=1447981902629859365) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859365&selected=1447981902629859365)     return fn(*args, **kwargs)
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859366&selected=1447981902629859366) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859366&selected=1447981902629859366)   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 534, in create_engine
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859367&selected=1447981902629859367) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859367&selected=1447981902629859367)     entrypoint = u._get_entrypoint()
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859368&selected=1447981902629859368) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859368&selected=1447981902629859368)   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 661, in _get_entrypoint
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859369&selected=1447981902629859369) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859369&selected=1447981902629859369)     cls = registry.load(name)
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859370&selected=1447981902629859370) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859370&selected=1447981902629859370)   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859371&selected=1447981902629859371) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859371&selected=1447981902629859371)     raise exc.NoSuchModuleError(
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902629859372&selected=1447981902629859372) [app/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aapp%2Fscheduler.4027&focus=1447981902629859372&selected=1447981902629859372) sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902646636550&selected=1447981902646636550) [heroku/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aheroku%2Fscheduler.4027&focus=1447981902646636550&selected=1447981902646636550) Process exited with status 1
Apr 05 12:50:10 [webcompat-metrics](https://my.papertrailapp.com/systems/webcompat-metrics/events?focus=1447981902721097737&selected=1447981902721097737) [heroku/scheduler.4027](https://my.papertrailapp.com/events?q=program%3Aheroku%2Fscheduler.4027&focus=1447981902721097737&selected=1447981902721097737) State changed from up to complete
```

**Comment by karlcow** [comment]
Mainly 

```
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
```

Ah maybe
https://stackoverflow.com/questions/62688256/sqlalchemy-exc-nosuchmoduleerror-cant-load-plugin-sqlalchemy-dialectspostgre

indeed the DATABASE_URL starts with `postgres://` instead of `postgresql://`

**Comment by karlcow** [comment]
@laghee if you can squeeze 10 minutes before me <3

**Comment by laghee** [comment]
Ohhhh... wait... the **heroku** URI. Gotcha. Let's see if I can get my new laptop configured enough to CLI in...

**Comment by karlcow** [comment]
Solved by @laghee with 
https://github.com/webcompat/webcompat-metrics-server/pull/151

**Pull request merged**
