### PR TITLE
Fixes #119 - Create script to upload back weekly total counts NO MERGE

### LINKED ISSUE #119: Move last bit of archived data (weekly reports) to DB
I'll have to run this manually through the Heroku cli, but I'll send in a PR for the script to make sure another set of eyes sees it first.

### PR DESCRIPTION
**Pull request by laghee**
This works locally with no problems. Let me know if you see anything amiss.

Once I get your thumbs-up, I'll go ahead and run it in production mode and we'll officially have everything pulling from our Heroku Postgres DB! 🎉 😃

### CODE REVIEW

**Comment by laghee** [comment]
Ooops, forgot to ping just in case: @karlcow

**Comment by laghee** [comment]
OK, @karlcow, AKA Marvin Gaye -- our DB is officially up to date now:   🎉 🎈 
Screenshot 2019-08-05 18 07 50

[Also see Heroku dataclip here](https://data.heroku.com/dataclips/dnehqneaczymkkazogzkokevhmvu)

**Comment by karlcow** [comment]
❤️ thanks laghee!

**Comment by karlcow** [comment]
@laghee should we close this?

**Pull request merged**
